# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1awYVECPdIXRLjYs80RYQKHF6kcPl-AMn

# faster rcnn

Faster R-CNN is a deep learning model that detects objects in images
"""

import torch
import torchvision
from torchvision import transforms
from torch import nn
from PIL import Image
import cv2
from google.colab.patches import cv2_imshow
import torchvision

model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)

model.eval()

!wget 'http://images.cocodataset.org/val2017/000000037777.jpg'

img = Image.open('/content/000000037777.jpg')

# converting the image into tensor
transformer = transforms.Compose([
    transforms.ToTensor(),
    transforms.Resize(size=(230,230))
])

img_tensor = transformer(img)
img_tensor.shape

with torch.inference_mode():
  pred = model([img_tensor])

pred

pred[0].keys()

boxes , labels , scores = pred[0]['boxes'] , pred[0]['labels'] , pred[0]['scores']

boxes.shape , labels.shape , scores.shape

num = torch.argwhere(scores > 0.9).shape[0] # shows the index position where the scores is greater that 0.9

coco_names = ["person" , "bicycle" , "car" , "motorcycle" , "airplane" , "bus" , "train" , "truck" , "boat" , "traffic light" , "fire hydrant" , "street sign" , "stop sign" , "parking meter" , "bench" , "bird" , "cat" , "dog" , "horse" , "sheep" , "cow" , "elephant" , "bear" , "zebra" , "giraffe" , "hat" , "backpack" , "umbrella" , "shoe" , "eye glasses" , "handbag" , "tie" , "suitcase" ,
"frisbee" , "skis" , "snowboard" , "sports ball" , "kite" , "baseball bat" ,
"baseball glove" , "skateboard" , "surfboard" , "tennis racket" , "bottle" ,
"plate" , "wine glass" , "cup" , "fork" , "knife" , "spoon" , "bowl" ,
"banana" , "apple" , "sandwich" , "orange" , "broccoli" , "carrot" , "hot dog" ,
"pizza" , "donut" , "cake" , "chair" , "couch" , "potted plant" , "bed" ,
"mirror" , "dining table" , "window" , "desk" , "toilet" , "door" , "tv" ,
"laptop" , "mouse" , "remote" , "keyboard" , "cell phone" , "microwave" ,
"oven" , "toaster" , "sink" , "refrigerator" , "blender" , "book" ,
"clock" , "vase" , "scissors" , "teddy bear" , "hair drier" , "toothbrush" , "hair brush"]

font = cv2.FONT_HERSHEY_SIMPLEX

# Read the image using OpenCV
img_array = cv2.imread('/content/000000037777.jpg') # reads the image as numpy array

# cv2_imshow(img_array)

for i in range(num):
  x1, y1 , x2,y2 = boxes[i].numpy().astype("int")
  print(x1 , y1 , x2 , y2)
  class_name = coco_names[labels.numpy()[i] - 1]
  img_array = cv2.rectangle(img_array,(x1,y1) , (x2,y2) , (0,255,0) , 1)
  img_array = cv2.putText(img_array , class_name , (x1,y1 -10), font , 0.5 , (255 , 0 , 0) , 1 , cv2.LINE_AA)

cv2_imshow(img_array)